// (c) Pix4D. AUTOGENERATED FILE. DO NOT MODIFY.
#pragma once


namespace px4d {

struct CameraParameters final {
    double sensorWidth;
    double focalLength;
    double imageWidth;
    double imageHeight;

    CameraParameters() = default;

    CameraParameters(double sensorWidth_,
                     double focalLength_,
                     double imageWidth_,
                     double imageHeight_)
    : sensorWidth(std::move(sensorWidth_))
    , focalLength(std::move(focalLength_))
    , imageWidth(std::move(imageWidth_))
    , imageHeight(std::move(imageHeight_))
    {}
};

}  // namespace px4d
