// (c) Pix4D. AUTOGENERATED FILE. DO NOT MODIFY.
#pragma once


namespace px4d {

struct Coordinate2D final {
    double latitude;
    double longitude;

    Coordinate2D() = default;

    Coordinate2D(double latitude_,
                 double longitude_)
    : latitude(std::move(latitude_))
    , longitude(std::move(longitude_))
    {}
};

}  // namespace px4d
