// (c) Pix4D. AUTOGENERATED FILE. DO NOT MODIFY.
#pragma once


namespace px4d {

struct Size final {
    double width;
    double height;

    Size() = default;

    Size(double width_,
         double height_)
    : width(std::move(width_))
    , height(std::move(height_))
    {}
};

}  // namespace px4d
